### ISSUE TITLE
WCF Service.Model issue

### ISSUE THREAD

**Issue by amccool** [amccool/AM.Elasticsearch.TraceListener#6]
[Field name [{http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord}TraceRecord] cannot contain '.']

```
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: [2017-01-24 12:02:02,278][DEBUG][action.admin.indices.mapping.put] [Ningal] failed to put mappings on indices [[trace-2017-01-24-18]], type [Trace] Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: MapperParsingException[Field name [{http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord}TraceRecord] cannot contain '.'] Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:277)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parse(ObjectMapper.java:197)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:309)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:222)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:118)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:549)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Jan 24 12:02:02 SmellyCat01 elasticsearch[576]: at java.lang.Thread.run(Thread.java:745)

```

**Comment by amccool** [comment]
<- write a unit test.   throw in elasticsearch-inside
